version: '3.9'

services:
  db:
    image: mysql
    container_name: inshkasql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=almazondb
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
  nodeInshka:
    depends_on:
      - db
    image: node
    links:
      - db
    container_name: projectnode
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=almazondb
      - DB_PORT=3306
    ports:
      - 4000:3000
    build: .
    command: node src/index.js
    restart: always
